### ISSUE TITLE
GTiff generation options

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#198]
* mapchete convert creates tifs with global bounds, clip output at the end, (COG Explorer issue)
* maybe a different GTiff profile
* when uploading to bucket error, 'LZW not implemented' cant upload

**Comment by ungarj** [comment]
Thanks @Scartography!

* GTiff bounds: when converting from a global dataset (i.e. a `TileDIrectory`) you will have to provide explicitly the output bounds. Currently these bounds are snapped to the process tile pyramid, which will be resolved in #199 
* Could you clarify what you mean by GTiff profile? Maybe predefined profiles, e.g. COG?
* Could you provide some code to replicate the issue?
