### ISSUE TITLE
use BIGTIFF at single GTiffWriter

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#224]
- In the code referenced below use bigtiff to enable writing huge GTiff files.
- Additionally if workers/concurrency reduced to 4 threads/cores (depending on usage), then almost unlimited GTiff creation is possible (tested with ~25GB GTiffs). Ideally adjust concurrency based on RAM something like 1 CPU to 8 GB ratio.
- This makes the size condition obsolete (Can be set to something like 200 000x200 000 pixelsize)

https://github.com/ungarj/mapchete/blob/ee764a2641d1dc1cef859a54313647cb12c523c6/mapchete/formats/default/gtiff.py#L415-L455
```
self._profile = dict(
            GTIFF_DEFAULT_PROFILE,
            driver="GTiff",
            transform=Affine(
                self.pyramid.pixel_x_size(self.zoom),
                0,
                bounds.left,
                0,
                -self.pyramid.pixel_y_size(self.zoom),
                bounds.top
            ),
            height=height,
            width=width,
            count=self.output_params["bands"],
            crs=self.pyramid.crs,
            bigtiff='YES',
**{kwargs}
```
Cheers,
Petr

**Comment by ungarj** [comment]
related to #217
