### ISSUE TITLE
create project logo

### ISSUE THREAD

**Issue by ungarj** [ungarj/mapchete#236]

**Comment by ungarj** [comment]
first draft:

![mapchete svg](https://user-images.githubusercontent.com/3802285/77227363-20e3b000-6b80-11ea-9971-17325933df45.png)

**Comment by StefanBrand** [comment]
What about this? (arranging tiles as an M) 😉 

![mapchete_mockup](https://user-images.githubusercontent.com/8948865/77924487-fbebed00-72a3-11ea-9613-e476d1f31129.png)

**Comment by ungarj** [comment]
I like it! Thanks @StefanBrand!

**Comment by StefanBrand** [comment]
Another quick sketch and the svgs of both ideas. 😁 
![mapchete_pyramid](https://user-images.githubusercontent.com/8948865/89635779-d604d380-d8a7-11ea-9439-e82b827a5b86.png)

[mapchete_logo_svgs.zip](https://github.com/ungarj/mapchete/files/5040819/mapchete_logo_svgs.zip)

**Comment by ungarj** [comment]
i'll go for the first draft for now as it also combines well with the mapchete Hub logo
