### ISSUE TITLE
catch more rasterio errors in read_raster_window

### ISSUE THREAD

**Issue by ungarj** [ungarj/mapchete#288]
https://github.com/ungarj/mapchete/blob/master/mapchete/io/raster.py#L300

When S3 buckets are under heavy load, rasterio sometimes also throws a `CRSError` and potentially others. If those files do exist, the read operation should be retried.

**Comment by Scartography** [comment]
Maybe rework the whole: https://github.com/ungarj/mapchete/blob/master/mapchete/io/raster.py#L300-L306 logic and try to catch everything under a `MapcheteIOError`?

**Comment by Scartography** [comment]
As it currently seems to trigger **endless Exception** loops see:

> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 245, in _get_warped_array
> dst_nodata=dst_nodata
> File "", line 2, in _rasterio_read
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
> logger)
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
> return f()
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 306, in _rasterio_read
> raise FileNotFoundError("%s not found" % input_file)
> FileNotFoundError: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif not found
> [2020-11-21 01:40:43,609: ERROR/ForkPoolWorker-5:70] error while reading file https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif not found
> Traceback (most recent call last):
> File "rasterio/_base.pyx", line 216, in rasterio._base.DatasetBase.init
> File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset
> File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
> rasterio._err.CPLE_OpenFailedError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 295, in _rasterio_read
> with rasterio.open(input_file, "r") as src:
> File "/usr/local/lib/python3.6/site-packages/rasterio/env.py", line 434, in wrapper
> return f(*args, **kwds)
> File "/usr/local/lib/python3.6/site-packages/rasterio/init.py", line 218, in open
> s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
> File "rasterio/_base.pyx", line 218, in rasterio._base.DatasetBase.init
> rasterio.errors.RasterioIOError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 245, in _get_warped_array
> dst_nodata=dst_nodata
> File "", line 2, in _rasterio_read
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
> logger)
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
> return f()
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 306, in _rasterio_read
> raise FileNotFoundError("%s not found" % input_file)
> FileNotFoundError: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif not found
> 2020-11-21 01:40:43,609 WARNING mapchete_satellite.utils._raster all bands empty, retrying in 1 seconds...
> [2020-11-21 01:40:43,609: WARNING/ForkPoolWorker-5:70] all bands empty, retrying in 1 seconds...
> 2020-11-21 01:40:45,209 ERROR mapchete.io.raster error while reading file https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif not found
> Traceback (most recent call last):
> File "rasterio/_base.pyx", line 216, in rasterio._base.DatasetBase.init
> File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset
> File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
> rasterio._err.CPLE_OpenFailedError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 295, in _rasterio_read
> with rasterio.open(input_file, "r") as src:
> File "/usr/local/lib/python3.6/site-packages/rasterio/env.py", line 434, in wrapper
> return f(*args, **kwds)
> File "/usr/local/lib/python3.6/site-packages/rasterio/init.py", line 218, in open
> s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
> File "rasterio/_base.pyx", line 218, in rasterio._base.DatasetBase.init
> rasterio.errors.RasterioIOError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 245, in _get_warped_array
> dst_nodata=dst_nodata
> File "", line 2, in _rasterio_read
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
> logger)
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
> return f()
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 306, in _rasterio_read
> raise FileNotFoundError("%s not found" % input_file)
> FileNotFoundError: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif not found
> 2020-11-21 01:40:45,209 ERROR mapchete.io.raster error while reading file https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif not found
> Traceback (most recent call last):
> File "rasterio/_base.pyx", line 216, in rasterio._base.DatasetBase.init
> File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset
> File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
> rasterio._err.CPLE_OpenFailedError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 295, in _rasterio_read
> with rasterio.open(input_file, "r") as src:
> File "/usr/local/lib/python3.6/site-packages/rasterio/env.py", line 434, in wrapper
> return f(*args, **kwds)
> File "/usr/local/lib/python3.6/site-packages/rasterio/init.py", line 218, in open
> s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
> File "rasterio/_base.pyx", line 218, in rasterio._base.DatasetBase.init
> rasterio.errors.RasterioIOError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 245, in _get_warped_array
> dst_nodata=dst_nodata
> File "", line 2, in _rasterio_read
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
> logger)
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
> return f()
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 306, in _rasterio_read
> raise FileNotFoundError("%s not found" % input_file)
> FileNotFoundError: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif not found
> [2020-11-21 01:40:45,209: ERROR/ForkPoolWorker-5:70] error while reading file https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif not found
> Traceback (most recent call last):
> File "rasterio/_base.pyx", line 216, in rasterio._base.DatasetBase.init
> File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset
> File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
> rasterio._err.CPLE_OpenFailedError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 295, in _rasterio_read
> with rasterio.open(input_file, "r") as src:
> File "/usr/local/lib/python3.6/site-packages/rasterio/env.py", line 434, in wrapper
> return f(*args, **kwds)
> File "/usr/local/lib/python3.6/site-packages/rasterio/init.py", line 218, in open
> s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
> File "rasterio/_base.pyx", line 218, in rasterio._base.DatasetBase.init
> rasterio.errors.RasterioIOError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 245, in _get_warped_array
> dst_nodata=dst_nodata
> File "", line 2, in _rasterio_read
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
> logger)
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
> return f()
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 306, in _rasterio_read
> raise FileNotFoundError("%s not found" % input_file)
> FileNotFoundError: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B08.tif not found
> 2020-11-21 01:40:45,210 ERROR mapchete.io.raster error while reading file https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif not found
> Traceback (most recent call last):
> File "rasterio/_base.pyx", line 216, in rasterio._base.DatasetBase.init
> File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset
> File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
> rasterio._err.CPLE_OpenFailedError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 295, in _rasterio_read
> with rasterio.open(input_file, "r") as src:
> File "/usr/local/lib/python3.6/site-packages/rasterio/env.py", line 434, in wrapper
> return f(*args, **kwds)
> File "/usr/local/lib/python3.6/site-packages/rasterio/init.py", line 218, in open
> s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
> File "rasterio/_base.pyx", line 218, in rasterio._base.DatasetBase.init
> rasterio.errors.RasterioIOError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 245, in _get_warped_array
> dst_nodata=dst_nodata
> File "", line 2, in _rasterio_read
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
> logger)
> 2020-11-21 01:40:45,210 ERROR mapchete.io.raster error while reading file https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif not found
> Traceback (most recent call last):
> File "rasterio/_base.pyx", line 216, in rasterio._base.DatasetBase.init
> File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset
> File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
> rasterio._err.CPLE_OpenFailedError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 295, in _rasterio_read
> with rasterio.open(input_file, "r") as src:
> File "/usr/local/lib/python3.6/site-packages/rasterio/env.py", line 434, in wrapper
> return f(*args, **kwds)
> File "/usr/local/lib/python3.6/site-packages/rasterio/init.py", line 218, in open
> s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
> File "rasterio/_base.pyx", line 218, in rasterio._base.DatasetBase.init
> rasterio.errors.RasterioIOError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 245, in _get_warped_array
> dst_nodata=dst_nodata
> File "", line 2, in _rasterio_read
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
> logger)
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
> return f()
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 306, in _rasterio_read
> raise FileNotFoundError("%s not found" % input_file)
> FileNotFoundError: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif not found
> [2020-11-21 01:40:45,210: ERROR/ForkPoolWorker-5:70] error while reading file https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif not found
> Traceback (most recent call last):
> File "rasterio/_base.pyx", line 216, in rasterio._base.DatasetBase.init
> File "rasterio/_shim.pyx", line 78, in rasterio._shim.open_dataset
> File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
> rasterio._err.CPLE_OpenFailedError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
> return f()
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 306, in _rasterio_read
> raise FileNotFoundError("%s not found" % input_file)
> FileNotFoundError: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif not found
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 295, in _rasterio_read
> with rasterio.open(input_file, "r") as src:
> File "/usr/local/lib/python3.6/site-packages/rasterio/env.py", line 434, in wrapper
> return f(*args, **kwds)
> File "/usr/local/lib/python3.6/site-packages/rasterio/init.py", line 218, in open
> s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
> File "rasterio/_base.pyx", line 218, in rasterio._base.DatasetBase.init
> rasterio.errors.RasterioIOError: '/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif' not recognized as a supported file format.
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 245, in _get_warped_array
> dst_nodata=dst_nodata
> File "", line 2, in _rasterio_read
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 74, in retry_decorator
> logger)
> File "/usr/local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
> return f()
> File "/usr/local/lib/python3.6/site-packages/mapchete/io/raster.py", line 306, in _rasterio_read
> raise FileNotFoundError("%s not found" % input_file)
> FileNotFoundError: https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/30V/XR2020/8/S2A_30VXR_20200810_0_L2A/B02.tif not found

**Comment by ungarj** [comment]
I'm wrapping the `read_raster_window()`, `read_raster_no_crs() and `read_vector_window()` functions to either raise an `MapcheteIOError` or a `FileNotFoundError`.
