### ISSUE TITLE
requirements: set s3fs minimum version to 0.5.1

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#310]
* for instance in the `rm` command of cli the s3 check shoud be `if "s3" in fs.protocol` as fs.protocol returns: `['s3', 's3a']`
    *  https://github.com/ungarj/mapchete/blob/master/mapchete/io/_path.py#L119 this does not trigger in its form

* start this issue to discuss, debug, etc.

**Comment by Scartography** [comment]
> 2020-12-11 15:12:36,100 DEBUG mapchete.io._path read next page
> Do you want to delete 805 tiles? [y/N]: y
> 2020-12-11 15:12:55,349 DEBUG mapchete.io._path got 805 path(s) on <s3fs.core.S3FileSystem object at 0x7f321328ed30>
> Traceback (most recent call last):
>   File "/home/suprd/miniconda3/envs/s2/bin/mapchete", line 11, in <module>
>     load_entry_point('mapchete', 'console_scripts', 'mapchete')()
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.6/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.6/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.6/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/cli/default/rm.py", line 91, in rm_
>     fs=src_fs
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/io/_path.py", line 123, in rm
>     fs.rm(paths, recursive=recursive)
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.6/site-packages/s3fs/core.py", line 990, in rm
>     bucket, key, _ = self.split_path(path)
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.6/site-packages/s3fs/core.py", line 245, in split_path
>     path = path.lstrip('/')
> AttributeError: 'list' object has no attribute 'lstrip'
>

**Comment by ungarj** [comment]
thanks! it seems installing `s3fs>=0.5.1` solves it.

**Comment by ungarj** [comment]
also, update the code according to petrs suggestion

**Comment by ungarj** [comment]
fixed by #311
