### ISSUE TITLE
`is_empty()` does check intersection not if the data is empty/there or not

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#315]
* Suggestion change `is_empty()` to `intersects()` https://github.com/ungarj/mapchete/blob/master/mapchete/formats/default/gtiff.py#L734-L743
*  the `is_empty` should be designed to check for empty data tiles based on missing tile as in the path or if numpy/xarray data being empty or fully masked (if `any()` return `False`)

**Comment by ungarj** [comment]
The `is_empty()` function is meant to only check whether the tile intersects with the dataset (i.e. it only asserts that there is definitively no data to read). You are right, it could be that the intersection holds a fully masked array. In that case the array returned by the read function returns a fully masked array.

This is mainly a performance feature as to conduct a more thorough check would mean actually open the file and look into it which would slow down the processing significantly.
