### ISSUE TITLE
config: collect process function arguments into a separate parameter

### ISSUE THREAD

**Issue by ungarj** [ungarj/mapchete#356]
currently, all unused (i.e. non-default) configuration parameters are considered as parameters to be passed on to the process function. this is a bit messy and leads to model validation issues (once we want to use pydantic).

we should specify all the process function arguments in a separate configuration option, e.g. a dict named `process_args`.

**Comment by Scartography** [comment]
...make classes based on pydantic `BaseModel` or do not validate arb. classes/functions as per:

> import pydantic
> 
> class Config:
>     arbitrary_types_allowed = True
> 
> 
> @pydantic.dataclasses.dataclass(config=Config)
> class MyFancyClass:
>     """I am Fancy."""

**Comment by ungarj** [comment]
closed by #564
