### ISSUE TITLE
mapchete convert throws ERROR in the latest release

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#390]
> Traceback (most recent call last):
>   File "/home/suprd/miniconda3/envs/s2/bin/mapchete", line 33, in <module>
>     sys.exit(load_entry_point('mapchete', 'console_scripts', 'mapchete')())
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.8/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.8/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.8/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/cli/default/convert.py", line 127, in convert
>     list(
>   File "/home/suprd/miniconda3/envs/s2/lib/python3.8/site-packages/tqdm/std.py", line 1185, in __iter__
>     for obj in iterable:
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/_processing.py", line 87, in __iter__
>     yield from self._run()
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/_processing.py", line 70, in _run
>     yield from self.func(*self.fargs, executor=self.executor, **self.fkwargs)
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/commands/_execute.py", line 197, in _process_everything
>     for process_info in mp.batch_processor(
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/_core.py", line 390, in batch_processor
>     for process_info in _run_area(
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/_processing.py", line 541, in _run_area
>     for process_info in _run_multi(
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/_processing.py", line 634, in _run_multi
>     for future in executor.as_completed(
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/_executor.py", line 483, in as_completed
>     for item in iterable:
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/_processing.py", line 636, in <genexpr>
>     iterable=(
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/_processing.py", line 584, in _filter_skipable
>     for tile, skip in process.skip_tiles(tiles_batches=tiles_batches):
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/_core.py", line 195, in skip_tiles
>     for batch in tiles_batches:
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/_core.py", line 158, in get_process_tiles
>     for tile in self.config.process_pyramid.tiles_from_geom(
>   File "/home/suprd/PycharmProjects/_Sentinel-2_mosaics/git/mapchete/mapchete/tile.py", line 134, in tiles_from_geom
>     for batch in self.tile_pyramid.tiles_from_geom(
> TypeError: tiles_from_geom() got an unexpected keyword argument 'batch_by'
>

**Comment by ungarj** [comment]
have you updated tilematrix as well?

**Comment by Scartography** [comment]
my bad!
