### ISSUE TITLE
avoid path_exists calls if possible

### ISSUE THREAD

**Issue by ungarj** [ungarj/mapchete#454]
e.g. when reading a Tile Directory on S3, this can result in a huge amount of requests: https://github.com/ungarj/mapchete/blob/master/mapchete/formats/base.py#L545

**Comment by Scartography** [comment]
Or try catching retrying s3 not available exeption: `botocore.exceptions.ClientError: An error occurred (503) when calling the HeadObject operation (reached max retries: 4): Service Unavailable` from ` File "/usr/local/lib/python3.8/site-packages/mapchete/_tasks.py", line 264, in _execute
   raise new`
