### ISSUE TITLE
Comparison with PyWPS

### ISSUE THREAD

**Issue by timiyay** [ungarj/mapchete#46]
Hi folks, sorry for making a GH issue on this, but I couldn't find a good way to get in touch.

I watched the FOSS4G presentation on this tool, and I'm very interested. `mapchete` looks great for my use case, trying to break a never-ending PostGIS spatial join query into bite-sized chunks.

During the FOSS4G presentation, in the questions, a crowd member stated something along the lines of:

> Why didn't you use PyWPS?... _It does everything_
> (emphasis added)

I'm currently verifying the truth behind that comment, and I'd love to hear the `mapchete` maintainers give their thoughts on the crossover between the 2 libraries, and what `PyWPS` is missing that `mapchete` provides.

I'm yet to start experimenting with either package, but I've read the docs and some source code for both. My initial (possibly incorrect) take is that:
- `mapchete` is focused on running custom geoprocessing jobs, while `PyWPS` is for creating a standards-compliant web server to wrap these geoprocessing jobs
- `mapchete` supports spatial tiling for processing jobs, `PyWPS` does not (this is a big one, arguably the main appeal of `mapchete`)
- `mapchete` is analagous to a geospatially-focused MapReduce library, while `PyWPS` is an open-source version of an ArcGIS Server Geoprocessing service
- `mapchete` uses modern Pythonic libraries such as `Fiona` and `rasterio` to assist with code-driven processing, while `PyWPS` requires the use of OGC-standard XML documents for running processes

It's probably evident that I'm excited about `mapchete`, and not excited about `PyWPS`. After 2 hours of research, including watching the FOSS4G presentation, I've concluded that the crowd comment was misleading, and I should ignore it and move forward with `mapchete`.

However, 2 hours isn't very much research, and I'm quite happy to be mistaken in my assumptions.

What are the main overlaps and differentiators between `mapchete` and `PyWPS`?

To be clear, my use case is for speeding up batch geoprocessing jobs for internal company use. I'm interested in the tiling mechanisms mostly. I don't need to create a OGC-compliant web server for XML-based geoprocessing - I already have a simple JSON API which allows me to trigger these jobs.

**Comment by ungarj** [comment]
Hi, no problem using a GitHub issue as we don't have a mailing list. It might even be helpful for others to follow such discussions via the GitHub issues.

I remember the comment at FOSS4G and when re-watching the presentation I realized I could have done a much better job to describe the concept behind ``mapchete``. From the beginning I should have emphasized more on the fact that ``mapchete`` processes tiles and tiles only as well as that these tiles are either the Web Mercator or geodetic WMTS tiles. This maybe could have clear up the questions regarding ``PyWPS`` and whether there will be support for other projections as well.

Tiling is the base concept and everything else is built around it. This of course is a limitation unless your output is used for a tiled web service. ``PyWPS`` didn't seem to support tiling natively, which was the starting point of ``mapchete``. I guess it would have been possible as well to write a tiling wrapper around ``PyWPS`` processes but it was too tempting to create something from scratch. However ``PyWPS`` provided a good example how to decouple a custom process from a processing engine. 

At some point in the future I would like to explore whether it would be possible to adjust ``mapchete`` in a way that it could run ``PyWPS`` processes as well and vice versa. Running processes is I think the main crossover between both, where ``mapchete`` simply focuses on tile based processing and outputs (which for some use cases is a limitation) while being able to run these processes either as a web service _or_ as a batch process on the command line and ``PyWPS`` being the more generic solution for any web-based geoprocessing.

> mapchete is focused on running custom geoprocessing jobs, while PyWPS is for creating a standards-compliant web server to wrap these geoprocessing jobs

I'm not an expert for ``PyWPS`` but I think one could state both _run_ geoprocessing jobs (even if both call e.g. a GRASS tool in the background). A ``PyWPS`` process gets invoked by an HTTP request but I guess you could also wrap it in a script as well. Hence, I don't see much difference in running geoprocessing jobs here.

> mapchete supports spatial tiling for processing jobs, PyWPS does not (this is a big one, arguably the main appeal of mapchete)

Exactly.

> mapchete is analagous to a geospatially-focused MapReduce library, while PyWPS is an open-source version of an ArcGIS Server Geoprocessing service

Again, not a ``PyWPS`` expert here as well as of MapReduce but from what I understood it is fair to say that it follows a similar concept as MapReduce. (If this assumption is wrong, I'm glad to learn more.)

> mapchete uses modern Pythonic libraries such as Fiona and rasterio to assist with code-driven processing, while PyWPS requires the use of OGC-standard XML documents for running processes

I'm not sure whether I understand correctly what you mean. If ``PyWPS`` is configured using an OGC-standard XML, the counterpart would be the YAML configuration file. As for Fiona and rasterio: both are great libraries. I tried to learn from the coding style and do my best to use it in ``mapchete`` as well.

As for your use case: Please be aware that the process outputs are always constrained to the tiling scheme. This means 

- For raster data that the output resolution cannot be set arbitrarily. It is always bound to the specified zoom level and the tile resolution (default 256x256 pixels).
- Vector data will always be clipped to the tile boundaries. This may be well intended (as probably for your use case) but would probably not fit with every single use case.
- No other output projection than Web Mercator (EPSG 3857) or WGS84/geodetic (EPSG 4326). Maybe for a future use case it would be possible allocate some effort in this. In the latest ``tilematrix`` release I tried to [parameterize the tile pyramid definitions](https://github.com/ungarj/tilematrix/blob/master/tilematrix/tilematrix.py#L14) which could probably help to add other projections.

Glad you like the tool and thank you for your effort looking into it. I would be happy to know the outcome of your research in comparing the two tools.
