### ISSUE TITLE
dask: dask-graph is not ignoring processed output

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#524]
* tasks are being done regardless of `overwrite` flag

**Comment by ungarj** [comment]
checked it and it seems that this occurs when using the task graph and the dask scheduler decides that in order to get the dependencies for a follow-up task (i.e. an overview tile task), it is cheaper to reprocess the base tile task instead of moving the base tile task result to a different worker.

**Comment by ungarj** [comment]
closing this for now as it seems to be a dask issue
