### ISSUE TITLE
GDAL COG warning when using `mapchete convert` with `--cog` option

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#584]
Check setup of the rasterio out profile accordingly.

Warning 6: driver COG does not support creation option BLOCKXSIZE
Warning 6: driver COG does not support creation option TILED
Warning 6: driver COG does not support creation option INTERLEAVE
Warning 6: driver COG does not support creation option BANDS
Warning 6: driver COG does not support creation option COG
Warning 6: driver COG does not support creation option COMPRESSION

**Comment by Scartography** [comment]
Also be careful when using WEBP with overviews: `Warning 6: driver COG does not support creation option WEBP_LOSSLESS`

**Comment by ungarj** [comment]
closed by #584
