### ISSUE TITLE
more sencible bounds from geometries around antimerian (add a flag)

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#598]
Some geometries may stretch across the globe when hitting antimeridian and will then not be properly in the bounds of the process area. Add a check or a flag to wrap these around and split them.

* {
    "type" : "Polygon",
    "coordinates" : [ [ [ 179.84209263611973, 66.68718991362921 ], [ -179.04432230152517, 66.7055905335068 ], [ -178.96620770878562, 65.72115713058994 ], [ 178.93922617949963, 65.67974995906643 ], [ 179.69500738745725, 66.52324086208313 ], [ 179.84209263611973, 66.68718991362921 ] ] ]
  }
* https://github.com/ungarj/mapchete/blob/d649f94a8a657d66b8925d5d7f78db2dd14511ef/mapchete/types.py#L98

**Comment by ungarj** [comment]
this issue is caused by code not from mapchete core
