### ISSUE TITLE
http input can use ENV variables for access, expand this to the whole mapchete yaml config to accept ENV variables?

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#624]
* based  on this: https://github.com/ungarj/mapchete/blob/main/test/testdata/env_storage_options.mapchete
* here `access_key: ${AK1}` accepts ENV variable, maybe if all the config could try to parse ENV variables like: `path: dummy2.tif` to be `path: ${INPUT_RASTER_PATH}`

**Comment by ungarj** [comment]
good idea, this!

**Comment by ungarj** [comment]
... and it already works :)

have you tried it?

**Comment by Scartography** [comment]
ah yeah it works, the ENV in the config needs the curly brackets to accept the pattern `${xxx}` not `$xxx`
