### ISSUE TITLE
protobuf version 3.20.1 officially only to python 3.10

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#628]
Old `protobuf` package version in dpes now quite outdated. Breaking `conda install mapchete` as this is not compatible via deps check in conda envs.

* https://github.com/ungarj/mapchete/blob/main/pyproject.toml#L62
 * https://pypi.org/project/protobuf/3.20.1/

**Comment by ungarj** [comment]
yeah let's remove the `Geobuf` driver:

* https://github.com/ungarj/mapchete/issues/596
* https://github.com/ungarj/mapchete/issues/472
