### ISSUE TITLE
config.parse.guess_geometry does not accept MultiPolygons for me

### ISSUE THREAD

**Issue by Scartography** [ungarj/mapchete#655]
* https://github.com/ungarj/mapchete/blob/main/mapchete/config/parse.py#L229-L232
* from `if not is_type(geom, "Polygon", singlepart_equivalent_matches=True)` to `if not is_type(geom, ("Polygon", "MultiPolygon"), singlepart_equivalent_matches=True)`
* Not sure here, but it should accept polygons as well as multipolys else with `MultiPolygon` I get: `area must either be a Polygon or a MultiPolygon, not MultiPolygon` which is well weird

**Comment by ungarj** [comment]
here you go: https://github.com/ungarj/mapchete/pull/656

**Comment by ungarj** [comment]
fixed and included in `2024.11.0`
